###obtener simuladores
GET http://localhost:3000/api/simulators

###crear simuladores
# @name createSimulators
POST http://localhost:3000/api/simulators
Content-Type: application/json

{
  "name": "Assetto Corsa",
  "status": "active"
}

### ID
@id = {{createSimulators.response.body.data.id}}

###obtener simulador por id
GET http://localhost:3000/api/simulators/{{id}}


###actualizar simulador (PUT)
PUT http://localhost:3000/api/simulators/{{id}}
Content-Type: application/json

{
  "name": "Assetto Corsa Competizione",
  "status": "active"
}

###actualizar solo estado de simulador (PATCH)
PATCH http://localhost:3000/api/simulators/{{id}}
Content-Type: application/json

{
  "status": "inactive"
}

###eliminar simulador
DELETE http://localhost:3000/api/simulators/{{id}}