###obtener membresias
GET http://localhost:3000/api/membresias

###crear membresia
# @name createMembresia
POST http://localhost:3000/api/membresias
Content-Type: application/json

{
  "descripcion": "Membresía Básica",
  "valorMembresia": 9.99
}

### ID
@id = {{createMembresia.response.body.data.id}}

###obtener membresia por id
GET http://localhost:3000/api/membresias/{{id}}


###actualizar membresia (PUT)
# PUT http://localhost:3000/api/membresias/{{id}}
# Content-Type: application/json

# {
  #"descripcion": "Membresía Premium",
  #"valorMembresia": 19.99
#}

###actualizar solo descripción de membresia (PATCH)
# PATCH http://localhost:3000/api/membresias/{{id}}
# Content-Type: application/json

# {
  # "descripcion": "Membresía Pro"
# }

###eliminar membresia
DELETE http://localhost:3000/api/membresias/{{id}}